### ISSUE TITLE
!ammo doesn't work or the Syntax is wrong?

### ISSUE THREAD

**Issue by ThiccMcButters** [Stefanuk12/ROBLOX#11]
howdy boss, just started using your script, and everything was working great, then i found a weapon and needed ammo.

long-story-short, the !ammo commands doesn't work for any of the ammo's. would love to see this fixed!

 - you're awesome

**Comment by Stefanuk12** [comment]
To confirm, this is for the [DospenserBot](https://github.com/Stefanuk12/ROBLOX/blob/master/Games/Decaying%20Winter/Stefanuk-ified/DispenserBot.lua)?

**Comment by Stefanuk12** [comment]
> howdy boss, just started using your script, and everything was working great, then i found a weapon and needed ammo.
> 
> 
> 
> long-story-short, the !ammo commands doesn't work for any of the ammo's. would love to see this fixed!
> 
> 
> 
>  - you're awesome

To confirm, this is for the [DispenserBot](https://github.com/Stefanuk12/ROBLOX/blob/master/Games/Decaying%20Winter/Stefanuk-ified/DispenserBot.lua)?

**Comment by ThiccMcButters** [comment]
That is correct

**Comment by Stefanuk12** [comment]
> That is correct

Unfortunately, I don't update these scripts. You could look at the original thread linked in the source.
