### ISSUE TITLE
Silent Aim [Rush Point]

### ISSUE THREAD

**Issue by timekalazar** [Stefanuk12/ROBLOX#12]
When an enemy is in your sight, it freezes your character and your camera, and you can't do anything until you die.

**Comment by Stefanuk12** [comment]
Just tested and it works fine. Are you using synapse?

**Comment by timekalazar** [comment]
I use KRNL cause I am poor, lmao

**Comment by timekalazar** [comment]
Doesn't it support KRNL?

**Comment by Stefanuk12** [comment]
> Doesn't it support KRNL?
> 
> 

Technically, yes. However, KRNL may not be optimised with debug.validlevel and debug.getupvalues

**Comment by timekalazar** [comment]
Ouch, is there a way you could fix that?

**Comment by timekalazar** [comment]
I'm sorry for the late responses. lol

**Comment by timekalazar** [comment]
Can I contact you on discord?
It is easier there for me to respond as I am really active there.

Destruss#3732

**Comment by Stefanuk12** [comment]
> Ouch, is there a way you could fix that?

Sadly not, I believe it's a fault with KRNL

**Comment by timekalazar** [comment]
That hurts.

**Comment by Stefanuk12** [comment]
"Resolved"
