### ISSUE TITLE
Rush Point

### ISSUE THREAD

**Issue by Fuz1on1** [Stefanuk12/ROBLOX#13]
The keybinds for the silent aim and aimlock would be? 

im using synapse

**Comment by Stefanuk12** [comment]
> The keybinds for the silent aim and aimlock would be? 
> 
> 
> 
> im using synapse

Silent aim has no keybind, it's on all the time. Aim lock is right mouse button.

**Comment by jLn0n** [comment]
offtopic but:
```lua
local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer
local script = LocalPlayer.PlayerScripts:FindFirstChild("Vortex")
local scriptEnvReq = {
	"Reload",
	"Restock",
	"GetAmmoData",
	"GatherWeaponData"
}
local function envLoaded(_env)
	for name in pairs(_env) do
		if table.find(scriptEnvReq, name) then
			return true
		end
	end
end

while true do task.wait()
	local scriptRunning, scriptEnv = pcall(getsenv, script)
	if (scriptRunning and scriptEnv) and envLoaded(scriptEnv) then
		hookfunction(scriptEnv.Reload, scriptEnv.Restock)
		debug.setupvalue(scriptEnv.GetAmmoData, 2, 0 / 0)
		debug.setupvalue(scriptEnv.GatherWeaponData, 4, 1000)
		local weaponData = debug.getupvalues(scriptEnv.GatherWeaponData, 5)[10]
		rawset(weaponData, "BaseVelocity", -100)
		rawset(weaponData, "Weight", 0)
	end
end
```

**Comment by Stefanuk12** [comment]
> offtopic but:
> 
> ```lua
> 
> local Players = game:GetService("Players")
> 
> local LocalPlayer = Players.LocalPlayer
> 
> local script = LocalPlayer.PlayerScripts:FindFirstChild("Vortex")
> 
> local scriptEnvReq = {
> 
> 	"Reload",
> 
> 	"Restock",
> 
> 	"GetAmmoData",
> 
> 	"GatherWeaponData"
> 
> }
> 
> local function envLoaded(_env)
> 
> 	for name in pairs(_env) do
> 
> 		if table.find(scriptEnvReq, name) then
> 
> 			return true
> 
> 		end
> 
> 	end
> 
> end
> 
> 
> 
> while true do task.wait()
> 
> 	local scriptRunning, scriptEnv = pcall(getsenv, script)
> 
> 	if (scriptRunning and scriptEnv) and envLoaded(scriptEnv) then
> 
> 		hookfunction(scriptEnv.Reload, scriptEnv.Restock)
> 
> 		debug.setupvalue(scriptEnv.GetAmmoData, 2, 0 / 0)
> 
> 		debug.setupvalue(scriptEnv.GatherWeaponData, 4, 1000)
> 
> 		local weaponData = debug.getupvalues(scriptEnv.GatherWeaponData, 5)[10]
> 
> 		rawset(weaponData, "BaseVelocity", -100)
> 
> 		rawset(weaponData, "Weight", 0)
> 
> 	end
> 
> end
> 
> ```

Please create a new bug report for this, explaining the bug with the game link and link to the script

**Comment by Stefanuk12** [comment]
Assume all is fixed
