### ISSUE TITLE
silent aim

### ISSUE THREAD

**Issue by melo58000** [Stefanuk12/ROBLOX#14]
hello, before i say anything iam using synapse but anyways, with the silent aim, when i execute it and aim at a person, the camera just freezes and i cant do anything. is there something im doing wrong or did they patch it?

**Comment by Stefanuk12** [comment]
> hello, before i say anything iam using synapse but anyways, with the silent aim, when i execute it and aim at a person, the camera just freezes and i cant do anything. is there something im doing wrong or did they patch it?

which game?

**Comment by melo58000** [comment]
> which game?

rush point.

**Comment by Stefanuk12** [comment]
Fixed

**Comment by melo58000** [comment]
thank you.

**Comment by melo58000** [comment]
is there a way i could possibly hide the fov circle?

**Comment by Stefanuk12** [comment]
You can view all of the configurable settings [here](https://stefanuk12.github.io/Aiming/aiming/settings/).

Example Usage:
```lua
Aiming.Settings.FOVSettings.Enabled = false
```

**Comment by melo58000** [comment]
> You can view all of the configurable settings [here](https://stefanuk12.github.io/Aiming/aiming/settings/).
> 
> Example Usage:
> 
> ```lua
> Aiming.Settings.FOVSettings.Enabled = false
> ```

k thank you, where would I be able to change the value at? or is there a specific line where I add it in at? I apologize but I don't code or make any scripts for Roblox so I'm really clueless when it comes to stuff like this.

**Comment by Stefanuk12** [comment]
> > You can view all of the configurable settings [here](https://stefanuk12.github.io/Aiming/aiming/settings/).
> 
> > 
> 
> > Example Usage:
> 
> > 
> 
> > ```lua
> 
> > Aiming.Settings.FOVSettings.Enabled = false
> 
> > ```
> 
> 
> 
> k thank you, where would I be able to change the value at? or is there a specific line where I add it in at? I apologize but I don't code or make any scripts for Roblox so I'm really clueless when it comes to stuff like this.

Execute afterward the main script stand-alone
