### ISSUE TITLE
Rush Point - Slient Aim

### ISSUE THREAD

**Issue by PhongRobloxVN** [Stefanuk12/ROBLOX#15]
Every time i execute the script, it just straight out freeze the game 

Executor: Synapse X
OS: Windows 11

**Comment by Stefanuk12** [comment]
> Every time i execute the script, it just straight out freeze the game 
> 
> 
> 
> Executor: Synapse X
> 
> OS: Windows 11
> 
> 

alright, will look into it soon. likely patched

**Comment by Stefanuk12** [comment]
Duplicate of #14
