### ISSUE TITLE
Why the chances of hitting a headshot so low?

### ISSUE THREAD

**Issue by PhongRobloxVN** [Stefanuk12/ROBLOX#16]
title

**Comment by Stefanuk12** [comment]
> title

I'm unable to help you much since you don't follow the bug report format. However, generally the hit chance is 100% and it's targeting the humanoid root part and the head. More than likely, you're aiming at the torso/closer to the HRP. In other words, aim above the head for best results.

**Comment by PhongRobloxVN** [comment]
oh yeah the slient aim not hitting people if there are 

> > title
> 
> I'm unable to help you much since you don't follow the bug report format. However, generally the hit chance is 100% and it's targeting the humanoid root part and the head. More than likely, you're aiming at the torso/closer to the HRP. In other words, aim above the head for best results.

Hi I really appreciate your quick reply, I tried the way you said above and it worked. But the thing that makes me don't understand why is that if the enemies are right behind things like boxes then the slient aim won't hit them eventhough my crosshair targeted the head

**Comment by Stefanuk12** [comment]
> oh yeah the slient aim not hitting people if there are 
> 
> 
> 
> > > title
> 
> > 
> 
> > I'm unable to help you much since you don't follow the bug report format. However, generally the hit chance is 100% and it's targeting the humanoid root part and the head. More than likely, you're aiming at the torso/closer to the HRP. In other words, aim above the head for best results.
> 
> 
> 
> Hi I really appreciate your quick reply, I tried the way you said above and it worked. But the thing that makes me don't understand why is that if the enemies are right behind things like boxes then the slient aim won't hit them eventhough my crosshair targeted the head

It's because half of the target is hidden. What it does is see if the middle of the target is visible, if it is then yeah
